apiVersion: v1
kind: Pod
metadata:
  name: insufficient-resources
spec:
  containers:
    - name: app
      image: nginx:latest
      resources:
        requests:
          memory: "8Gi"  # Solicita demasiada memoria
          cpu: "250m"
