apiVersion: v1
kind: Pod
metadata:
  name: labels-mismatch
  labels:
    app: app-label  # Etiqueta del pod
spec:
  containers:
    - name: app
      image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: labels-mismatch
  labels:
    service: service-label  # Etiqueta del servicio
spec:
  selector:
    app: wrong-label  # Etiqueta incorrecta, no coincide con la del pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
