apiVersion: v1
kind: Pod
metadata:
  name: env-vars-missing
spec:
  containers:
    - name: app
      image: nginx:latest
      env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: non-existent-configmap  # ConfigMap no existe
              key: api-url
