apiVersion: v1
kind: ConfigMap
metadata:
  name: valid-configmap
data:
  api-url: "https://my-api.com"
---
apiVersion: v1
kind: Pod
metadata:
  name: env-vars-missing
spec:
  containers:
    - name: app
      image: nginx:latest
      env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: valid-configmap
              key: api-url
