apiVersion: v1
kind: Pod
metadata:
  name: sufficient-resources
spec:
  containers:
    - name: app
      image: nginx:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
