apiVersion: v1
kind: Pod
metadata:
  name: labels-matched
  labels:
    app: app-label
spec:
  containers:
    - name: app
      image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: labels-mismatch
  labels:
    service: service-label
spec:
  selector:
    app: app-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
